---
# Main playbook to deploy complete Kubernetes cluster
- import_playbook: 00-ha.yml
- import_playbook: 01-common.yaml
- import_playbook: 02-cluster-init-master.yaml
- import_playbook: 03-join-master.yaml
- import_playbook: 03-join-worker.yaml